import { Song } from "@/types/antakshari";

/**
 * Sample Songs Dataset for Antakshari Battle Foundation
 * NOTE: Does NOT contain copyrighted full song lyrics.
 * Uses short traditional snippets, public domain folk chants, or placeholder metadata only.
 */
export const SAMPLE_SONGS: Song[] = [
  // ── Assamese folk / Bihu ────────────────────────────────────────────────
  {
    id: "as-bihu-001",
    title: "Bihu Re Bihu",
    language: "Assamese",
    region: "Assam",
    artist: "Traditional Folk",
    startingSyllable: "B",
    lyricsSnippet: "Bihu re bihu lagise gaa...",
    category: "assamese_folk_bihu",
    tags: ["bihu", "folk", "spring", "traditional", "dhol"],
  },
  {
    id: "as-bihu-002",
    title: "O Mur Apunar Desh",
    language: "Assamese",
    region: "Assam",
    artist: "Lakshminath Bezbaroa",
    startingSyllable: "O",
    lyricsSnippet: "O mur apunar desh, o mur sikuni desh...",
    category: "assamese_folk_bihu",
    tags: ["anthem", "patriotic", "assamese", "heritage"],
  },
  {
    id: "as-bihu-003",
    title: "Mur Minoti",
    language: "Assamese",
    region: "Assam",
    artist: "Dr. Bhupen Hazarika",
    startingSyllable: "M",
    lyricsSnippet: "Mur gaan jodi he...",
    category: "assamese_folk_bihu",
    tags: ["bhupen_da", "melody", "classic", "cultural"],
  },
  {
    id: "as-bihu-004",
    title: "Keteki Binale",
    language: "Assamese",
    region: "Assam",
    artist: "Traditional Folk",
    startingSyllable: "K",
    lyricsSnippet: "Keteki binale ku-ku sore...",
    category: "assamese_folk_bihu",
    tags: ["bihu", "nature", "folk", "rhythm"],
  },

  // ── Naga folk ────────────────────────────────────────────────────────────
  {
    id: "naga-folk-001",
    title: "Ayo O Kuki",
    language: "Naga Folk",
    region: "Nagaland",
    artist: "Traditional Naga Ensemble",
    startingSyllable: "A",
    lyricsSnippet: "Traditional Naga community harvest melody snippet...",
    category: "naga_folk",
    tags: ["naga", "harvest", "choral", "folk", "traditional"],
  },
  {
    id: "naga-folk-002",
    title: "Lole Lole Song",
    language: "Naga Folk",
    region: "Nagaland",
    artist: "Traditional Choral",
    startingSyllable: "L",
    lyricsSnippet: "Festival choral harmony snippet honoring tribal fellowship...",
    category: "naga_folk",
    tags: ["festival", "fellowship", "choral", "nagaland"],
  },
  {
    id: "naga-folk-003",
    title: "Holi Hornbill Chant",
    language: "Nagamese",
    region: "Nagaland",
    artist: "Folk Troupe",
    startingSyllable: "H",
    lyricsSnippet: "Hornbill celebratory welcome rhythm snippet...",
    category: "naga_folk",
    tags: ["hornbill", "celebration", "drum", "folk"],
  },

  // ── Northeast Indian regional songs ──────────────────────────────────────
  {
    id: "ne-reg-001",
    title: "Chingkheirol Melody",
    language: "Manipuri",
    region: "Manipur",
    artist: "Traditional Pena Player",
    startingSyllable: "C",
    lyricsSnippet: "Traditional Pena morning invocation snippet...",
    category: "northeast_regional",
    tags: ["manipuri", "pena", "morning", "invocation"],
  },
  {
    id: "ne-reg-002",
    title: "Khasi Hills Echo",
    language: "Khasi",
    region: "Meghalaya",
    artist: "Traditional Troupe",
    startingSyllable: "K",
    lyricsSnippet: "Mountain breeze flute rhythm snippet...",
    category: "northeast_regional",
    tags: ["meghalaya", "khasi", "hills", "acoustic"],
  },
  {
    id: "ne-reg-003",
    title: "Mizo Cheraw Beat",
    language: "Mizo",
    region: "Mizoram",
    artist: "Traditional Bamboo Ensemble",
    startingSyllable: "M",
    lyricsSnippet: "Bamboo dance rhythmic cadence snippet...",
    category: "northeast_regional",
    tags: ["cheraw", "mizoram", "bamboo_dance", "folk"],
  },

  // ── Bollywood classics ───────────────────────────────────────────────────
  {
    id: "bw-classic-001",
    title: "Mera Joota Hai Japani",
    language: "Hindi",
    region: "Pan-India",
    artist: "Mukesh",
    startingSyllable: "M",
    lyricsSnippet: "Mera joota hai Japani, ye patloon Inglistani...",
    category: "bollywood_classics",
    tags: ["golden_era", "classic", "cheerful", "retro"],
  },
  {
    id: "bw-classic-002",
    title: "Yeh Shaam Mastani",
    language: "Hindi",
    region: "Pan-India",
    artist: "Kishore Kumar",
    startingSyllable: "Y",
    lyricsSnippet: "Yeh shaam mastani, madhosh kiye jaaye...",
    category: "bollywood_classics",
    tags: ["evergreen", "kishore_kumar", "melody", "evening"],
  },
  {
    id: "bw-classic-003",
    title: "Pyaar Hua Iqraar Hua",
    language: "Hindi",
    region: "Pan-India",
    artist: "Manna Dey, Lata Mangeshkar",
    startingSyllable: "P",
    lyricsSnippet: "Pyaar hua iqraar hua hai, pyaar se phir kyu darta hai dil...",
    category: "bollywood_classics",
    tags: ["rain", "duet", "classic", "monsoon"],
  },
  {
    id: "bw-classic-004",
    title: "Kabhi Kabhi Mere Dil Mein",
    language: "Hindi",
    region: "Pan-India",
    artist: "Mukesh",
    startingSyllable: "K",
    lyricsSnippet: "Kabhi kabhi mere dil mein khayaal aata hai...",
    category: "bollywood_classics",
    tags: ["nostalgia", "poetry", "classic", "sahir"],
  },

  // ── Other Indian regional songs ──────────────────────────────────────────
  {
    id: "oth-reg-001",
    title: "Aami Kolkatar Rosogolla",
    language: "Bengali",
    region: "West Bengal",
    artist: "Traditional Folk",
    startingSyllable: "A",
    lyricsSnippet: "Festive celebration chorus snippet...",
    category: "other_regional",
    tags: ["bengali", "festive", "traditional", "folklore"],
  },
  {
    id: "oth-reg-002",
    title: "Kadavul Ullame",
    language: "Tamil",
    region: "Tamil Nadu",
    artist: "Classic Ensemble",
    startingSyllable: "K",
    lyricsSnippet: "Classic Carnatic inspired melody snippet...",
    category: "other_regional",
    tags: ["tamil", "classic", "melody", "carnatic"],
  },
  {
    id: "oth-reg-003",
    title: "Maithili Madhur Gaan",
    language: "Maithili",
    region: "Bihar",
    artist: "Vidyapati Tradition",
    startingSyllable: "M",
    lyricsSnippet: "Traditional seasonal Maithili song snippet...",
    category: "other_regional",
    tags: ["maithili", "vidyapati", "folk", "traditional"],
  },
];
